export const villageDirectory = {
	Executive: {
		VillageHall: {
			address: "375 W. Briarcliff Road",
			id: "VillageHall",
			phone: "(630) 226-8400",
			fax: "(630) 226-8409",
			title: "Village Hall",
			name: "Main Office",
		},
		Mayor: {
			name: "Mary Alexander-Basta",
			id: "MaryAlexanderBasta",
			phone: "(630) 226-8412",
			cell: "(630) 280-4819",
			email: "mayormary@bolingbrook.com",
			title: "Mayor",
			profileLink: "https://www.bolingbrook.com/?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=0D89AE7E-8639-4C4E-8A3D-7A6FA65D1EF2",
			profilePath: "/MayorMary",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Mary_Basta_2019.png)",
				backgroundSize: "210px",
				backgroundPositionY: "-5px",
				backgroundPositionX: "0px",
			},
		},
		TrusteeRupsis: {
			name: "Aimee Rupsis",
			phone: "(630) 226-8417",
			email: "Email Needed",
			title: "Village Trustee",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/index.asp?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=508ED333-D119-44A0-8C8E-B05EE3435B2E",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Aimee_Rupsis_Headshot.jpg)",
				backgroundSize: "230px",
				backgroundPositionY: "0px",
				backgroundPositionX: "-12px",
			},
		},
		TrusteeLawler: {
			name: "Michael T. Lawler",
			phone: "(630) 226-8417",
			email: "Email Needed",
			title: "Village Trustee",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=2B389FD4-2233-42DC-8438-E762563FEDCD",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Michael_Lawler_Village_Trustee_2017_cropped.PNG)",
				backgroundSize: "200px",
				backgroundPositionY: "-10px",
				backgroundPositionX: "5px",
			},
		},
		TrusteeCarpanzano: {
			name: "Michael Carpanzano",
			phone: "(630) 226-8417",
			email: "Email Needed",
			title: "Village Trustee",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=CF668DFE-FF34-4C7F-AB1E-07C6B339B64D",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Michael_Carpanzano_2019.png)",
				backgroundSize: "200px",
				backgroundPositionY: "-10px",
				backgroundPositionX: "5px",
			},
		},
		TrusteeZarate: {
			name: "Maria A. Zarate",
			phone: "(630) 226-8417",
			email: "Email Needed",
			title: "Village Trustee",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=B3F45964-3CF0-42BE-8745-4505BAE43EA1",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Maria_Web.jpg)",
				backgroundSize: "200px",
				backgroundPositionY: "-10px",
				backgroundPositionX: "5px",
			},
		},
		TrusteeWatts: {
			name: "Sheldon L. Watts",
			phone: "(630) 226-8417",
			email: "Email Needed",
			title: "Village Trustee",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=154E2106-BF2F-4A27-9DBE-C09E79BAD24E",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Trustee_Sheldon_L._Watts.jpg)",
				backgroundSize: "250px",
				backgroundPositionY: "0px",
				backgroundPositionX: "-15px",
			},
		},
		TrusteeDoris: {
			name: "Troy J. Doris",
			id: "TrusteeDoris",
			phone: "(630) 226-8417",
			email: "Email Needed",
			title: "Village Trustee",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/index.asp?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=85425B34-934A-4A84-93D9-2CF9DCC93ED1",
			image: {
				backgroundImage:
					"url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/Troy_Profile_Picture.jpg)",
				backgroundSize: "235px",
				backgroundPositionY: "-15px",
				backgroundPositionX: "-30px",
			},
		},

		CoAdministrator1: {
			name: "Ken Teppel",
			id: "CoAdministrator1",
			phone: "(630) 226-8696",
			email: "kteppel@bolingbrook.com",
			title: "Co-Administrator",
		},
		CoAdministrator2: {
			name: "Lucas Rickelman",
			id: "CoAdministrator2",
			phone: "(630) 226-8805",
			email: "lrickelm@bolingbrook.com",
			title: "Co-Administrator",
		},
		Clerk: {
			name: "Martha 'Marti' M. Barton",
			id: "Clerk",
			phone: "(630) 226-8411",
			email: "mbarton@bolingbrook.com",
			title: "Village Clerk",
			profilePath: "/trusteeRupsis",
			profileLink: "https://www.bolingbrook.com/index.asp?SEC=0506393A-9DFE-4C7C-905C-C4D2609F079A&DE=8C7C1162-6514-456F-B0B5-345DC5511BA6",
			image: {
				backgroundImage: "url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/mmb_2020.jpg)",
				backgroundSize: "230px",
				backgroundPositionY: "-25px",
				backgroundPositionX: "-15px",
			},
		},
		DeputyClerk: {
			name: "Crystal Tovar",
			id: "DeputyClerk",
			phone: "(630) 226-8413",
			email: "Need Email",
			title: "Deputy Village Clerk",
		},
		AsstDeputyClerk: {
			name: "Sandy Clark",
			phone: "(630) 226-8423",
			email: "Need Email",
			title: "Assistant Deputy Village Clerk",
		},
		Attorney: {
			name: "(Odelson, Sterk, Murphey, Frazier, McGrath, LTD)",
			id: "VillageAttorney",
			phone: "(630) 226-8412",
			title: "Village Attorney",
		},
		Trustees: {
			phone: "(630) 226-8416",
			email: "executive@bolingbrook.com",
			title: "Trustees",
		},
		FOIA: {
			name: "Fran Miller",
			id: "FreedomOfInformation",
			phone: "(630) 226-8414",
			email: "foia@bolingbrook.com",
			title: "FOIA Officer",
		},
		AsstFOIA: {
			name: "Art McGuigan",
			id: "ArtMcGuigan",
			phone: "(630) 226-8582",
			email: "Need Email",
			title: "Assistant FOIA Officer",
		},
		HumanResources: {
			name: "Human Resources",
			id: "HumanResources",
			phone: "(630) 226-8435",
			email: "vobhumanresources@bolingbrook.com",
			title: "Human Resources Office",
			fax: "(630) 226-8459",
		},
	},

	Commissions: {
		ArtsCouncil: {
			ArtsCouncil: {
				email: "bolingbrookartscouncil@gmail.com",
				name: "Arts Council",
				title: "Arts Council",
				id: "ArtsCouncil",
			},
			Chair: {
				name: "Mithra Zaucha",
				id: "ArtsChair",
				title: "Chair",
			},
			ViceChair: {
				name: "Hilary Rosenthal",
				id: "ArtsViceChair",
				title: "Vice-Chair",
			},
			Members: [
				"Mioara Barcutean",
				"Ed Gardner",
				"Julie Guida",
				"Marilyn Hernandez",
				"Allaina Humphreys",
				"Darleen Kay",
				"Janice Kessl",
				"Ocie Koonce",
				"Linda Lawrence",
				"Adrienne Ledbetter",
				"Regina McClay",
				"Ritu Rana",
				"Jose Rojas",
				"Bobbie Speer",
				"Deepti Suri",
				"Grace Tucker",
			],
		},
		IT: {
			Chair: {
				name: "Jerry Gynac",
				id: "ITChair",
				title: "Chair",
				email: "chair@vobitc.org",
			},
			ViceChair: {
				name: "Karl Natschke",
				id: "ITViceChair",
				title: "Vice-Chair",
			},
			Liason: {
				name: "James Farrell",
				id: "ITLiason",
				title: "CIO at the Village / Liason",
			},
			Members: [
				"Anirudh (Rudy) Kapadia",
				"Elden P. Laffoon, Sr.",
				"Meredith Walker",
				"Sean Walker",
				"Toni Washington",
				"Eric McIntyre",
				"Gwendolyn Arrington",
				"Ron Stork",
				"Karl Natschke",
				"Brian Dennis",
				"Lakshmi Anumalasetty",
				"Steve Mertes",
			],
		},
		Beautification: {
			Chair: {
				name: "Phyllis Ann Ruggiero",
				id: "BeautyChair",
				title: "Chair",
				email: "Phyllis-ann@att.net",
			},
			ViceChair: {
				name: "Barbara Ann Parker",
				email: "parkernycbabs@yahoo.com",
				id: "BeautyViceChair",
				title: "Vice-Chair",
			},

			Members: [
				"Lola Fashina",
				"Mary Hoffman",
				"Susan Jagiel",
				"Bobbi Massi",
				"Mary Myers",
				"Ron Supalo",
				"Timothy Wade",
				"Richard Zihala",
				"Laura Teipe",
				"Scott Fagust",
				"Evelyn Fletcher",
				"Debi Savage",
				"Jeanne Thompson",
				"Roy Herman",
				"Iva Asenova",
				"Cheryl Burger",
				"Andrea Boyles",
			],
		},
	},
	Police: {
		AnimalControl: {
			name: "Main Line",
			id: "AnimalControl",
			title: "Animal Control",
			phone: "(630) 226-8500",
		},
		AnimalControlSupervisor: {
			name: "Linda Laketa",
			id: "AnimalControlSupervisor",
			phone: "(630) 226-8412",
			title: "Animal Control Supervisor",
		},
		PoliceChief: {
			name: "Mike Rompa",
			id: "PoliceChief",
			phone: "(630) 226-8412",
			email: "mayormary@bolingbrook.com",
			title: "Chief of Police",
			image: {
				backgroundImage: "url(https://bolingbrookil.govoffice3.com/vertical/Sites/%7B55EB27CA-CA9F-40A5-A0EF-1E4EEF52F39E%7D/uploads/940.jpg)",
				backgroundSize: "210px",
				backgroundPositionY: "-5px",
				backgroundPositionX: "-12px",
			},
		},
		AfterHours: {
			name: "After Hours",
			id: "AfterHours",
			phone: "(630) 226-8670",
			title: "After Hours",
		},
		Investigations: {
			name: "Investigations",
			id: "Investigations",
			phone: "(630) 226-8620",
			title: "Investigations",
		},
		CodeEnforcement: {
			name: "Main Line",
			id: "CodeEnforcement",
			phone: "(630) 226-8760",
			title: "Code Enforcement",
		},
		CodeEnforcementSupervisor: {
			name: "Randy Kainrath",
			phone: "(630) 226-8765",
			email: "rkainrath@bolingbrook.com",
			title: "Code Enforcement Supervisor",
		},
		Evidence: {
			name: "Evidence",
			id: "Evidence",
			phone: "(630) 226-8620",
			title: "Evidence",
		},
		PoliceAdministration: {
			name: "Police Administration",
			id: "PoliceAdministration",
			phone: "(630) 226-8600",
			email: "police@bolingbrook.com",
			title: "Police Administration",
		},
	},

	Fire: {
		FireAdministration: {
			name: "Main Line",
			id: "FireAdministration",
			phone: "(630) 226-8540",
			email: "fire@bolingbrook.com",
			title: "Fire Administration",
		},
		FireChief: {
			name: "Jeff LaJoie",
			id: "JeffLaJoie",
			phone: "(630) 226-8696",
			email: "Need Email",
			title: "Fire Chief",
		},
		FireMarshal: {
			name: "Brian Gaston",
			id: "BrianGaston",
			phone: "(630) 226-8696",
			email: "Need Email",
			title: "Fire Marshall",
		},

		BattalionChief1: {
			name: "Todd Nemeth",
			id: "ToddNemeth",
			phone: "(630) 226-8532",
			email: "Need Email",
			title: "Battalion Chief / EMS Director",
		},
		BattalionChief2: {
			name: "Troy Kirch",
			id: "TroyKirch",
			phone: "(630) 226-8531",
			email: "Need Email",
			title: "Battalion Chief / EMS Director",
		},

		BattalionChief3: {
			name: "Ron Banda",
			id: "RonBanda",
			phone: "(630) 226-8524",
			email: "Need Email",
			title: "Battalion Chief",
		},
		BattalionChief4: {
			name: "Joe Fagan",
			id: "JoeFagan",
			phone: "(630) 226-8523",
			email: "Need Email",
			title: "Battalion Chief",
			level: 3,
		},

		BattalionChief5: {
			name: "Dan Ross",
			id: "DanRoss",
			phone: "(630) 226-8525",
			email: "Need Email",
			title: "Battalion Chief",
			level: 3,
		},
		FireAdminAid: {
			name: "Meghan Strimel",
			id: "FireAdminAid",

			title: "Administrative Aid",
		},
		FireSecretary: {
			name: "Justin Gomez",
			id: "FireSecretary",

			title: "Secretary",
		},
	},
};

export const organizationChart = [
	{
		name: "Executive Office",
		id: "ExecutiveOffice",
		level: 1,
		children: [
			{
				name: "Mary Alexander-Basta",
				id: "MaryAlexanderBasta",
				phone: "(630) 226-8412",
				email: "mayormary@bolingbrook.com",
				title: "Mayor",
				level: 1,
				children: [
					{
						name: "Martha 'Marti' M. Barton",
						id: "MartiBarton",
						phone: "(630) 226-8411",
						email: "mbarton@bolingbrook.com",
						title: "Village Clerk",
						level: 2,
						children: [
							{
								name: "Crystal Tovar",
								id: "CrystalTovar",
								phone: "(630) 226-8413",
								email: "Need Email",
								title: "Deputy Village Clerk",
								level: 3,
								children: [
									{
										name: "Sandy Clark",
										id: "SandyClark",
										phone: "(630) 226-8423",
										email: "Need Email",
										title: "Assistant Deputy Village Clerk",
										level: 4,
									},
								],
							},
						],
					},
					{
						name: "Ken Teppel",
						id: "KenTeppel",
						phone: "(630) 226-8696",
						email: "kteppel@bolingbrook.com",
						title: "Co-Administrator(Public Safety)",
						level: 2,
						children: [
							{
								level: 3,
								name: "Police Department",
								id: "PoliceDepartment",
							},
							{
								level: 3,
								name: "Fire Department",
								id: "FireDepartment",
							},
						],
					},
					{
						name: "Lucas Rickelman",
						id: "LucasRickelman",
						phone: "(630) 226-8805",
						email: "lrickelm@bolingbrook.com",
						title: "Co-Administrator",
						level: 2,
					},
					{
						name: "Fran Miller",
						id: "FranMiller",
						phone: "(630) 226-8414",
						email: "foia@bolingbrook.com",
						title: "FOIA Officer",
						level: 2,
						children: [
							{
								name: "Art McGuigan",
								id: "ArtMcGuigan",
								phone: "(630) 226-8582",
								email: "Need Email",
								title: "Assistant FOIA Officer",
								level: 3,
							},
						],
					},
				],
			},
		],
	},
	{
		name: "Fire Department",
		id: "FireDepartmentMain",
		level: 1,
		children: [
			{
				name: "Jeff LaJoie",
				id: "JeffLaJoie",
				phone: "(630) 226-8696",
				email: "Need Email",
				title: "Fire Chief",
				level: 1,
				children: [
					{
						name: "Fire Prevention Bureau",
						id: "FirePreventionBureau",
						level: 2,
						children: [
							{
								name: "Brian Gaston",
								id: "BrianGaston",
								phone: "(630) 226-8696",
								email: "Need Email",
								title: "Fire Marshall",
								level: 3,
								children: [
									{
										name: "Scott Bovyn",
										id: "ScottBovyn",
										phone: "(630) 226-8544",
										email: "Need Email",
										title: "Inspector",
										level: 4,
									},
									{
										name: "Nicole McGowan",
										id: "NicoleMcGowan",
										phone: "(630) 226-8544",
										email: "Need Email",
										title: "Inspector",
										level: 4,
									},
									{
										name: "Frank Ritter",
										id: "FrankRitter",
										phone: "(630) 226-8553",
										email: "Need Email",
										title: "Inspector",
										level: 4,
									},
								],
							},
						],
					},
					{
						name: "EMS",
						id: "EMS",
						level: 2,
						children: [
							{
								name: "Todd Nemeth",
								id: "ToddNemeth",
								phone: "(630) 226-8532",
								email: "Need Email",
								title: "Battalion Chief / EMS Director",
								level: 3,
							},
						],
					},
					{
						name: "Training",
						id: "Training",
						level: 2,
						children: [
							{
								name: "Troy Kirch",
								id: "TroyKirch",
								phone: "(630) 226-8531",
								email: "Need Email",
								title: "Battalion Chief / EMS Director",
								level: 3,
							},
						],
					},
					{
						name: "Battalion Chiefs",
						id: "BattalionChiefs",
						level: 2,
						children: [
							{
								name: "Ron Banda",
								id: "RonBanda",
								phone: "(630) 226-8524",
								email: "Need Email",
								title: "Battalion Chief",
								level: 3,
							},
							{
								name: "Joe Fagan",
								id: "JoeFagan",
								phone: "(630) 226-8523",
								email: "Need Email",
								title: "Battalion Chief",
								level: 3,
							},

							{
								name: "Dan Ross",
								id: "DanRoss",
								phone: "(630) 226-8525",
								email: "Need Email",
								title: "Battalion Chief",
								level: 3,
							},
						],
					},
				],
			},
		],
	},
];
